import Head from "next/head";
import Image from "next/image";
import styled from "styled-components";

import Sidebar from "../components/Sidebar";
import LandingInfo from "../components/LandingInfo";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Buyonia - Chat</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/icon.png" />
        <link
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
          crossOrigin="anonymous"
        />
      </Head>
      <Container>
        <Sidebar />
        <LandingInfo />
      </Container>
    </div>
  );
}

const Container = styled.div`
  display: flex;
`;
